"""Curated international artists for diverse track discovery."""

# (artist name, Spotify market hint)
INTERNATIONAL_ARTISTS: list[tuple[str, str]] = [
    ("Billie Eilish", "US"), ("Taylor Swift", "US"), ("Drake", "US"), ("Beyoncé", "US"),
    ("The Weeknd", "US"), ("Kendrick Lamar", "US"), ("Ariana Grande", "US"), ("Post Malone", "US"),
    ("Rihanna", "US"), ("Frank Ocean", "US"), ("Lana Del Rey", "US"), ("Tyler, The Creator", "US"),
    ("SZA", "US"), ("Bad Bunny", "US"), ("Rosalía", "ES"), ("Shakira", "CO"),
    ("J Balvin", "CO"), ("Karol G", "CO"), ("Feid", "CO"), ("Maluma", "CO"),
    ("Anitta", "BR"), ("Luísa Sonza", "BR"), ("Gilberto Gil", "BR"), ("Caetano Veloso", "BR"),
    ("Stromae", "FR"), ("Angèle", "FR"), ("Damso", "FR"), ("Orelsan", "FR"),
    ("Ed Sheeran", "GB"), ("Adele", "GB"), ("Dua Lipa", "GB"), ("Harry Styles", "GB"),
    ("Arctic Monkeys", "GB"), ("Radiohead", "GB"), ("Coldplay", "GB"), ("Amy Winehouse", "GB"),
    ("Rammstein", "DE"), ("Nena", "DE"), ("AnnenMayKantereit", "DE"), ("Clueso", "DE"),
    ("Måneskin", "IT"), ("Laura Pausini", "IT"), ("Mahmood", "IT"), ("Elodie", "IT"),
    ("BTS", "KR"), ("BLACKPINK", "KR"), ("NewJeans", "KR"), ("IU", "KR"),
    ("Stray Kids", "KR"), ("SEVENTEEN", "KR"), ("TWICE", "KR"), ("BIGBANG", "KR"),
    ("YOASOBI", "JP"), ("Official HIGE DANdism", "JP"), ("Aimyon", "JP"), ("Kenshi Yonezu", "JP"),
    ("King Gnu", "JP"), ("Ado", "JP"), ("LiSA", "JP"), ("ONE OK ROCK", "JP"),
    ("A.R. Rahman", "IN"), ("Arijit Singh", "IN"), ("Shreya Ghoshal", "IN"), ("Badshah", "IN"),
    ("Pritam", "IN"), ("Diljit Dosanjh", "IN"), ("AP Dhillon", "IN"), ("Anirudh Ravicher", "IN"),
    ("Burna Boy", "NG"), ("Wizkid", "NG"), ("Davido", "NG"), ("Tems", "NG"),
    ("Sarkodie", "GH"), ("Diamond Platnumz", "TZ"), ("Master KG", "ZA"), ("Black Coffee", "ZA"),
    ("Amadou & Mariam", "ML"), ("Angélique Kidjo", "BJ"), ("Fela Kuti", "NG"), ("Youssou N'Dour", "SN"),
    ("Céu", "BR"), ("Mon Laferte", "CL"), ("Juanes", "CO"), ("Monchy & Alexandra", "DO"),
    ("Marc Anthony", "US"), ("Romeo Santos", "US"), ("Prince Royce", "US"), ("Natti Natasha", "DO"),
    ("Sevdaliza", "NL"), ("Goldband", "NL"), ("S10", "NL"), ("Froukje", "NL"),
    ("Silvana Estrada", "MX"), ("Natalia Lafourcade", "MX"), ("Carla Morrison", "MX"), ("Christian Nodal", "MX"),
    ("Peso Pluma", "MX"), ("Junior H", "MX"), ("Eslabon Armado", "MX"), ("Fuerza Regida", "MX"),
    ("Tarkan", "TR"), ("Sezen Aksu", "TR"), ("Hadise", "TR"), ("Manga", "TR"),
    ("Zara Larsson", "SE"), ("Robyn", "SE"), ("ABBA", "SE"), ("Avicii", "SE"),
    ("Sia", "AU"), ("Tame Impala", "AU"), ("Kylie Minogue", "AU"), ("Flume", "AU"),
    ("Niska", "FR"), ("PNL", "FR"), ("Jul", "FR"), ("Gims", "FR"),
    ("Municipal Waste", "US"), ("Metallica", "US"), ("Nirvana", "US"), ("Green Day", "US"),
    ("Bob Marley", "JM"), ("Sean Paul", "JM"), ("Koffee", "JM"), ("Chronixx", "JM"),
    ("Bob Dylan", "US"), ("Joni Mitchell", "CA"), ("Leonard Cohen", "CA"), ("Neil Young", "CA"),
    ("Céline Dion", "CA"), ("The Tragically Hip", "CA"), ("Drake", "CA"), ("The Weeknd", "CA"),
    ("Phoebe Bridgers", "US"), ("Bon Iver", "US"), ("Fleet Foxes", "US"), ("Mitski", "US"),
    ("Clairo", "US"), ("Mac DeMarco", "US"), ("Tame Impala", "AU"), ("Khruangbin", "US"),
    ("Daft Punk", "FR"), ("Justice", "FR"), ("Moderat", "DE"), ("Caribou", "CA"),
    ("Fred again..", "GB"), ("Disclosure", "GB"), ("Jamie xx", "GB"), ("Four Tet", "GB"),
    ("Travis Scott", "US"), ("Future", "US"), ("21 Savage", "US"), ("Playboi Carti", "US"),
    ("Nicki Minaj", "US"), ("Megan Thee Stallion", "US"), ("Doja Cat", "US"), ("Cardi B", "US"),
    ("Burna Boy", "NG"), ("Rema", "NG"), ("Fireboy DML", "NG"), ("Omah Lay", "NG"),
    ("Mitski", "US"), ("Japanese Breakfast", "US"), ("Jay Som", "US"), ("Alvvays", "CA"),
    ("Zion & Lennox", "PR"), ("Wisin & Yandel", "PR"), ("Ozuna", "PR"), ("Myke Towers", "PR"),
    ("Camilo", "CO"), ("Sech", "PA"), ("Farruko", "PR"), ("Daddy Yankee", "PR"),
    ("Mohamed Ramadan", "EG"), ("Amr Diab", "EG"), ("Sherine", "EG"), ("Cairokee", "EG"),
    ("Fairuz", "LB"), ("Nancy Ajram", "LB"), ("Elissa", "LB"), ("Mashrou' Leila", "LB"),
    ("Phum Viphurit", "TH"), ("Palmy", "TH"), ("Slot Machine", "TH"), ("Bodyslam", "TH"),
    ("Rich Brian", "ID"), ("Niki", "ID"), ("Weird Genius", "ID"), ("Tulus", "ID"),
    ("Ben&Ben", "PH"), ("SB19", "PH"), ("Moira Dela Torre", "PH"), ("Sarah Geronimo", "PH"),
    ("Heize", "KR"), ("Crush", "KR"), ("DEAN", "KR"), ("Zico", "KR"),
    ("V", "KR"), ("Jung Kook", "KR"), ("Jimin", "KR"), ("Lisa", "TH"),
    ("Morgan Wallen", "US"), ("Luke Combs", "US"), ("Kacey Musgraves", "US"), ("Chris Stapleton", "US"),
    ("Johnny Hallyday", "FR"), ("Indochine", "FR"), ("Mylène Farmer", "FR"), ("Christine and the Queens", "FR"),
    ("Vance Joy", "AU"), ("Angus & Julia Stone", "AU"), ("Courtney Barnett", "AU"), ("Tash Sultana", "AU"),
    ("Rosé", "KR"), ("Jennie", "KR"), ("Taeyeon", "KR"), ("Red Velvet", "KR"),
    ("Måneskin", "IT"), ("Maneskin", "IT"), ("Elisa", "IT"), ("Tiziano Ferro", "IT"),
    ("Raphael", "FR"), ("Louane", "FR"), ("Vitaa", "FR"), ("Slimane", "FR"),
    ("Soolking", "DZ"), ("Mohamed Ramadan", "EG"), ("Saad Lamjarred", "MA"), ("Hatika", "MA"),
    ("G-Eazy", "US"), ("Logic", "US"), ("J. Cole", "US"), ("Nas", "US"),
    ("Eminem", "US"), ("50 Cent", "US"), ("Kanye West", "US"), ("Jay-Z", "US"),
    ("Shania Twain", "CA"), ("Carrie Underwood", "US"), ("Keith Urban", "AU"), ("Dolly Parton", "US"),
    ("Phoenix", "FR"), ("Air", "FR"), ("M83", "FR"), ("Yelle", "FR"),
    ("Woodkid", "FR"), ("Christine and the Queens", "FR"), ("Parcels", "AU"), ("Tame Impala", "AU"),
]
