#!/usr/bin/env python3
"""Write data/diverse_tracks.txt from curated artist + hit song pairs."""

from pathlib import Path

# artist -> up to 3 well-known vocal tracks (Genius-friendly)
ARTIST_HITS: dict[str, list[str]] = {
    "Billie Eilish": ["bad guy", "Happier Than Ever", "Therefore I Am"],
    "Taylor Swift": ["Anti-Hero", "Blank Space", "Cruel Summer"],
    "Drake": ["God's Plan", "One Dance", "Hotline Bling"],
    "Beyoncé": ["Halo", "Crazy in Love", "Break My Soul"],
    "The Weeknd": ["Blinding Lights", "Starboy", "Save Your Tears"],
    "Kendrick Lamar": ["HUMBLE.", "Alright", "DNA."],
    "Ariana Grande": ["7 rings", "thank u, next", "positions"],
    "Post Malone": ["Circles", "Sunflower", "rockstar"],
    "Rihanna": ["Umbrella", "We Found Love", "Diamonds"],
    "Frank Ocean": ["Thinkin Bout You", "Novacane", "Pink + White"],
    "Lana Del Rey": ["Summertime Sadness", "Video Games", "Young and Beautiful"],
    "Tyler, The Creator": ["See You Again", "EARFQUAKE", "NEW MAGIC WAND"],
    "SZA": ["Kill Bill", "Snooze", "Good Days"],
    "Bad Bunny": ["Tití Me Preguntó", "Dákiti", "Moscow Mule"],
    "Rosalía": ["Malamente", "Despechá", "Con Altura"],
    "Shakira": ["Hips Don't Lie", "Waka Waka", "BZRP Music Sessions #53"],
    "J Balvin": ["Mi Gente", "Ginza", "Ay Vamos"],
    "Karol G": ["TQG", "Provenza", "Bichota"],
    "Feid": ["Normal", "Chorrito Pa Las Animas", "Ferxxo 100"],
    "Maluma": ["Felices los 4", "Hawái", "Corazón"],
    "Anitta": ["Envolver", "Girl From Rio", "Versions of Me"],
    "Luísa Sonza": ["Penhasco", "Saudade Louca", "Campo de Morango"],
    "Stromae": ["Alors on danse", "Papaoutai", "Formidable"],
    "Angèle": ["Balance ton quoi", "Flou", "Ta reine"],
    "Ed Sheeran": ["Shape of You", "Perfect", "Thinking Out Loud"],
    "Adele": ["Hello", "Someone Like You", "Rolling in the Deep", "Set Fire to the Rain", "Skyfall", "Easy On Me"],
    "Dua Lipa": ["Levitating", "Don't Start Now", "New Rules"],
    "Harry Styles": ["As It Was", "Watermelon Sugar", "Sign of the Times"],
    "Arctic Monkeys": ["Do I Wanna Know?", "505", "R U Mine?"],
    "Radiohead": ["Creep", "Karma Police", "No Surprises"],
    "Coldplay": ["Yellow", "Fix You", "Viva La Vida"],
    "Rammstein": ["Du Hast", "Sonne", "Deutschland"],
    "Måneskin": ["Beggin'", "I Wanna Be Your Slave", "Gossip"],
    "Laura Pausini": ["La solitudine", "Non c'è", "Surrender"],
    "BTS": ["Dynamite", "Butter", "Spring Day"],
    "BLACKPINK": ["Kill This Love", "DDU-DU DDU-DU", "How You Like That"],
    "NewJeans": ["Ditto", "Super Shy", "OMG"],
    "IU": ["Celebrity", "Through the Night", "Love poem"],
    "Stray Kids": ["God's Menu", "Thunderous", "MANIAC"],
    "TWICE": ["Feel Special", "Fancy", "The Feels"],
    "YOASOBI": ["Idol", "Racing into the Night", "Gunjō"],
    "Kenshi Yonezu": ["Lemon", "Paprika", "KICK BACK"],
    "Ado": ["Usseewa", "New Genesis", "Show"],
    "Arijit Singh": ["Tum Hi Ho", "Raabta", "Kesariya"],
    "Shreya Ghoshal": ["Teri Meri", "Saans", "Chikni Chameli"],
    "Pritam": ["Kesariya", "Tum Se Hi", "Gerua"],
    "Diljit Dosanjh": ["Lover", "Do You Know", "G.O.A.T."],
    "Burna Boy": ["Last Last", "Ye", "On the Low", "Anybody"],
    "Wizkid": ["Essence", "Ojuelegba", "Joro", "Smile", "No Stress"],
    "Davido": ["Fall", "If", "Unavailable"],
    "Tems": ["Free Mind", "Essence", "Try Me"],
    "Marc Anthony": ["Vivir Mi Vida", "You Sang to Me", "I Need to Know"],
    "Romeo Santos": ["Propuesta Indecente", "Eres Mía", "Imitadora"],
    "Natalia Lafourcade": ["Hasta la Raíz", "Nunca Es Suficiente", "Tú sí sabes quererme"],
    "Carla Morrison": ["Disfruto", "Te Amo", "Eres tú"],
    "Peso Pluma": ["Ella Baila Sola", "AMG", "La Bebe"],
    "Tarkan": ["Şımarık", "Kuzu Kuzu", "Dudu"],
    "Sezen Aksu": ["Firuze", "Gülümse", "Hadi Bakalım"],
    "Zara Larsson": ["Lush Life", "Never Forget You", "Ruin My Life"],
    "Robyn": ["Dancing on My Own", "Call Your Girlfriend", "With Every Heartbeat"],
    "ABBA": ["Dancing Queen", "Mamma Mia", "The Winner Takes It All"],
    "Avicii": ["Wake Me Up", "The Nights", "Hey Brother"],
    "Sia": ["Chandelier", "Elastic Heart", "Cheap Thrills"],
    "Tame Impala": ["The Less I Know The Better", "Let It Happen", "Feels Like We Only Go Backwards"],
    "Kylie Minogue": ["Can't Get You Out of My Head", "Spinning Around", "Padam Padam"],
    "Bob Marley": ["Three Little Birds", "No Woman, No Cry", "Redemption Song"],
    "Bob Dylan": ["Like a Rolling Stone", "Blowin' in the Wind", "The Times They Are A-Changin'"],
    "Céline Dion": ["My Heart Will Go On", "The Power of Love", "Because You Loved Me"],
    "Phoebe Bridgers": ["Kyoto", "Motion Sickness", "Garden Song"],
    "Bon Iver": ["Holocene", "Skinny Love", "For Emma"],
    "Mitski": ["My Love Mine All Mine", "Washing Machine Heart", "First Love/Late Spring"],
    "Daft Punk": ["Get Lucky", "One More Time", "Harder, Better, Faster, Stronger"],
    "Fred again..": ["Marea (we’ve lost dancing)", "Delilah (pull me out of this)", "Kyle (I Found You)"],
    "Travis Scott": ["SICKO MODE", "goosebumps", "FE!N"],
    "Future": ["Mask Off", "Life Is Good", "WAIT FOR U"],
    "Nicki Minaj": ["Super Bass", "Anaconda", "Starships"],
    "Doja Cat": ["Say So", "Kiss Me More", "Paint The Town Red"],
    "Ozuna": ["Criminal", "Se Preparó", "Dile Que Tú Me Quieres"],
    "Daddy Yankee": ["Gasolina", "Con Calma", "Despacito"],
    "Camilo": ["Tutu", "Vida de Rico", "Indigo"],
    "Amr Diab": ["Tamally Maak", "Nour El Ein", "Baba"],
    "Fairuz": ["Sa'altak Habibi", "Kifak Inta", "Nassam Alayna El Hawa"],
    "Ben&Ben": ["Kathang Isip", "Leaves", "Maybe the Night"],
    "Heize": ["And July", "Happen", "We Don't Talk Together"],
    "Morgan Wallen": ["Last Night", "Whiskey Glasses", "Wasted on You"],
    "Luke Combs": ["Beautiful Crazy", "When It Rains It Pours", "Forever After All"],
    "Kacey Musgraves": ["Slow Burn", "Rainbow", "Follow Your Arrow"],
    "Johnny Hallyday": ["Que je t'aime", "Allumer le feu", "Marie"],
    "Indochine": ["L'Aventurier", "3 nuits par semaine", "Trois nuits par semaine"],
    "Eminem": ["Lose Yourself", "Without Me", "The Real Slim Shady"],
    "Jay-Z": ["Empire State of Mind", "99 Problems", "Ni**as in Paris"],
    "Metallica": ["Enter Sandman", "Nothing Else Matters", "Master of Puppets"],
    "Nirvana": ["Smell Like Teen Spirit", "Come As You Are", "Heart-Shaped Box"],
    "Fleetwood Mac": ["Dreams", "The Chain", "Go Your Own Way"],
    "Prince": ["Purple Rain", "When Doves Cry", "Kiss"],
    "Whitney Houston": ["I Will Always Love You", "I Wanna Dance with Somebody", "Greatest Love of All"],
    "Michael Jackson": ["Billie Jean", "Beat It", "Thriller"],
    "Madonna": ["Like a Prayer", "Vogue", "Hung Up"],
    "Elton John": ["Your Song", "Rocket Man", "Tiny Dancer"],
    "Queen": ["Bohemian Rhapsody", "Don't Stop Me Now", "Somebody to Love"],
    "The Beatles": ["Hey Jude", "Let It Be", "Yesterday"],
    "Led Zeppelin": ["Stairway to Heaven", "Whole Lotta Love", "Immigrant Song"],
    "Pink Floyd": ["Wish You Were Here", "Comfortably Numb", "Another Brick in the Wall"],
    "Amy Winehouse": ["Back to Black", "Rehab", "You Know I'm No Good"],
    "Alicia Keys": ["Fallin'", "If I Ain't Got You", "No One", "Girl on Fire", "Empire State of Mind (Part II)", "Underdog"],
    "Usher": ["Yeah!", "Burn", "U Got It Bad"],
    "Bruno Mars": ["Just the Way You Are", "Uptown Funk", "When I Was Your Man"],
    "Khalid": ["Location", "Talk", "Young Dumb & Broke"],
    "H.E.R.": ["Best Part", "Focus", "Damage"],
    "Lizzo": ["Truth Hurts", "Good as Hell", "About Damn Time"],
    "Selena Gomez": ["Lose You to Love Me", "Hands to Myself", "Same Old Love"],
    "Justin Bieber": ["Sorry", "Love Yourself", "Peaches"],
    "Shawn Mendes": ["Stitches", "Treat You Better", "There's Nothing Holdin' Me Back"],
    "OneRepublic": ["Counting Stars", "Apologize", "Secrets"],
    "Imagine Dragons": ["Radioactive", "Believer", "Demons"],
    "Twenty One Pilots": ["Stressed Out", "Heathens", "Ride"],
    "Linkin Park": ["In the End", "Numb", "Crawling"],
    "Red Hot Chili Peppers": ["Californication", "Under the Bridge", "Can't Stop"],
    "Oasis": ["Wonderwall", "Don't Look Back in Anger", "Champagne Supernova"],
    "Blur": ["Song 2", "Parklife", "Girls & Boys"],
    "The Killers": ["Mr. Brightside", "Somebody Told Me", "Human"],
    "Florence + The Machine": ["Dog Days Are Over", "Shake It Out", "You've Got the Love"],
    "Sam Smith": ["Stay With Me", "Too Good at Goodbyes", "Unholy"],
    "Lewis Capaldi": ["Someone You Loved", "Before You Go", "Forget Me"],
    "James Arthur": ["Say You Won't Let Go", "Impossible", "Car's Outside"],
    "George Ezra": ["Budapest", "Shotgun", "Green Green Grass"],
    "Hozier": ["Take Me to Church", "Someone New", "Work Song"],
    "Vance Joy": ["Riptide", "Georgia", "Fire and the Flood"],
    "Tones and I": ["Dance Monkey", "Fly Away", "Bad Child"],
    "Gotye": ["Somebody That I Used to Know", "Eyes Wide Open", "Hearts a Mess"],
    "Sade": ["Smooth Operator", "No Ordinary Love", "By Your Side"],
    "John Legend": ["All of Me", "Ordinary People", "Glory"],
    "Andrea Bocelli": ["Con te partirò", "Time to Say Goodbye", "Vivo per lei"],
    "Enrique Iglesias": ["Bailando", "Hero", "El Perdedor"],
    "Luis Fonsi": ["Despacito", "No Me Doy Por Vencido", "Aquí Estoy Yo"],
    "Alejandro Sanz": ["Corazón Partío", "La Quiero a Morir", "Amiga mía", "Y, ¿Si Fuera Ella?", "No Tengo Nada", "Mi Soledad y Yo"],
    "Juanes": ["La Camisa Negra", "A Dios le Pido", "Es Por Ti"],
    "Mon Laferte": ["Tu Falta de Querer", "Amárrame", "Tormento"],
    "Silvana Estrada": ["Te Guardo", "La Llorona", "La Sansa"],
    "Caetano Veloso": ["Sozinho", "Leaozinho", "Tropicália"],
    "Gilberto Gil": ["Aquele Abraço", "Palco", "Expresso 2222"],
    "Seu Jorge": ["Carolina", "Burguesinha", "Changes", "Tive Razão"],
    "Manu Chao": ["Clandestino", "Me Gustas Tu", "Bongo Bong"],
    "Calle 13": ["Latinoamérica", "Atrevete-te-te", "Atrévete-te-te"],
    "Residente": ["Despacito", "Latinoamérica", "This Is Not America"],
    "Gloria Estefan": ["Conga", "Rhythm Is Gonna Get You", "1-2-3"],
    "Celia Cruz": ["La Vida Es Un Carnaval", "Quimbara", "Bemba Colorá"],
    "Selena": ["Bidi Bidi Bom Bom", "Como La Flor", "Dreaming of You"],
    "Vicente Fernández": ["Volver, Volver", "El Rey", "La Diferencia"],
    "Chalino Sánchez": ["Alma Enamorada", "Nieves de Enero", "Florita del Alma"],
    "Los Tigres del Norte": ["La Puerta Negra", "Contrabando y Traición", "Jefe de Jefes"],
    "Aventura": ["Obsesión", "Un Beso", "Dile al Amor"],
    "CNCO": ["Reggaetón Lento", "Hey DJ", "Se Vuelve Loca"],
    "Reik": ["Creo En Ti", "Noviembre Sin Ti", "Me Niego"],
    "Morat": ["Cuando Nadie Ve", "Amor con Hielo", "Cómo Te Atreves"],
    "Camila Cabello": ["Havana", "Never Be the Same", "Bam Bam"],
    "Becky G": ["Mayores", "Sin Pijama", "Shower"],
    "Farruko": ["Pepas", "La Ocasion", "Chillax"],
    "Myke Towers": ["Lala", "Girl", "Si Se Da"],
    "Sech": ["Otro Trago", "Relación", "911"],
    "Anuel AA": ["China", "Adicto", "Secreto"],
    "Arcángel": ["Pa' Que La Pases Bien", "Hace Mucho Tiempo", "Me Acostumbré"],
    "Wisin": ["Escápate Conmigo", "Adrenalina", "Nota de Amor"],
    "Yandel": ["Encantadora", "Explícale", "Nunca Me Olvides"],
    "Zion & Lennox": ["La Player (Bandolera)", "Otra Vez", "More"],
    "Gente de Zona": ["La Gozadera", "Bailando", "Traficante"],
    "Gloria Trevi": ["Con los Ojos Cerrados", "Todos Me Miran", "No Querías Lastimarme"],
    "Thalía": ["Amor a la Mexicana", "Entre el Mar y una Estrella", "Piel Morena"],
    "Paulina Rubio": ["Y Yo Sigo Aquí", "Delfín", "Ni Una Sola Palabra"],
    "Luis Miguel": ["La Incondicional", "Ahora Te Puedes Marchar", "Hasta Que Me Olvides"],
    "Raphael": ["Escándalo", "Yo Soy Aquel", "Como Yo Te Amo"],
    "Mecano": ["Hijo de la Luna", "La Fuerza del Destino", "Me Cuesta Tanto Olvidarte"],
    "Héroes del Silencio": ["Entre Dos Tierras", "La Chispa Adecuada", "Avalancha"],
    "Jarabe de Palo": ["La Flaca", "Depende", "Bonito"],
    "Melendi": ["Camino de Rosas", "Con la Luna Llena", "Destino o Casualidad"],
    "Pablo Alborán": ["Solamente Tú", "Prometo", "Tabú"],
    "Aitana": ["Teléfono", "Formentera", "Stranger"],
    "Rels B": ["A Mí", "Como Canta un Bolero", "Lo Que Hay x Aquí"],
    "Quevedo": ["BZRP Music Sessions #52", "Catalina", "Playa del Inglés"],
    "Morad": ["Paris", "Lamine", "Son clases"],
    "Nathy Peluso": ["SANA SANA", "Delito", "Business Woman"],
    "Trueno": ["Dance Crip", "Tierra Zanta", "FKG"],
    "Emicida": ["AmarElo", "Levanta e Anda", "Passarinhos"],
    "Liniker": ["Calmô", "Zero", "Coração Negro"],
    "Djavan": ["Oceano", "Se...", "Essa Mina É Louca"],
    "Ivete Sangalo": ["Sorte Grande", "Acelera Aê", "Festa"],
    "Ludmilla": ["Cheguei", "Rainha da Favela", "Verdinha"],
    "MC Kevin o Chris": ["Tumbalacatumba", "Terça-feira Gostosa", "Ela É Sensacional"],
    "Alok": ["Hear Me Now", "Don't Say Goodbye", "Ocean"],
    "Jorge & Mateus": ["Os Anjos Cantam", "A Gente Não Se Aguenta", "Vou Voando"],
    "Henrique & Juliano": ["Cuida Bem Dela", "Até You Liberar", "Rancorosa"],
    "Marília Mendonça": ["Infiel", "Supera", "Todo Mundo Menos Eu"],
    "Zé Neto & Cristiano": ["Largado às Traças", "Notificação Preferida", "Status Que Eu Não Queria"],
    "Simone & Simaria": ["Regime Fechado", "Meu Violão e o Nosso Cão", "Página de Amigos"],
    "Angélique Kidjo": ["Agolo", "Wombo Lombo", "Djin Djin"],
    "Youssou N'Dour": ["7 Seconds", "Birima", "Set"],
    "Fela Kuti": ["Water No Get Enemy", "Zombie", "Lady"],
    "Rema": ["Calm Down", "Dumebi", "Iron Man"],
    "Fireboy DML": ["Peru", "Vibration", "Champion"],
    "Omah Lay": ["Bad Influence", "Understand", "Damn"],
    "Tyla": ["Water", "Been Thinking", "Jump"],
    "Ayra Starr": ["Rush", "Bloody Samaritan", "Commas"],
    "Asake": ["Joha", "Organise", "Sungba"],
    "Sarkodie": ["Adonai", "Landlord", "Happy Day"],
    "Diamond Platnumz": ["Jeje", "Waah!", "Mwanza"],
    "Sauti Sol": ["Suzanna", "Melanin", "Short N Sweet"],
    "Ali Gatie": ["It's You", "Moonlight", "What If I Told You That I Love You"],
    "Faouzia": ["Tears of Gold", "Hero", "RIP, Love"],
    "Rauf & Faik": ["Я люблю...", "Детство", "Колыбельная"],
    "Miyagi & Andy Panda": ["Kosandra", "Minor", "I Got Love"],
    "Mot": ["Капкан", "Оставь меня", "По барам"],
    "Zivert": ["Life", "Credo", "Beverly Hills"],
    "Morgenshtern": ["Cadillac", "Dulo", "El Problema"],
    "Egor Kreed": ["Самая самая", "Love Is", "Discoteka"],
    "Jony": ["Комета", "Титры", "Love Your Voice"],
    "Maksim": ["Трудный возраст", "Знаешь ли ты", "Не отпускай"],
    "Polina Gagarina": ["Кукушка", "Спектакль окончен", "Нет"],
    "Phum Viphurit": ["Lover Boy", "The History of Us", "Softly"],
    "Slot Machine": ["Give It All", "Jackpot", "Get Up and Go"],
    "Rich Brian": ["Dat $tick", "Kids", "Edible"],
    "Niki": ["Every Summertime", "Lowkey", "I Like U"],
    "Tulus": ["Monaco", "Hati-Hati di Jalan", "Temani Hidupku"],
    "Raisa": ["Anganku Anganmu", "Teka-Teki", "Usai di Sini"],
    "Agnez Mo": ["Coke Bottle", "Damn I Love You", "Overdose"],
    "Moira Dela Torre": ["Malaya", "Paubaya", "Tagpuan"],
    "Sarah Geronimo": ["Tala", "Kilometro", "Geronimo's Medley"],
    "SB19": ["Go Up", "Hanggang sa Huli", "Mapa"],
    "December Avenue": ["Sa Ngalan ng Pag-ibig", "Huling Sandali", "Kung Di Rin Lang Ikaw"],
    "IV of Spades": ["Mundo", "Come Inside Of My Heart", "Take That Man"],
    "Taeyeon": ["INVU", "Fine", "Weekend"],
    "Red Velvet": ["Psycho", "Bad Boy", "Feel My Rhythm"],
    "BIGBANG": ["Fantastic Baby", "Bang Bang Bang", "Loser", "FXXK IT", "Bae Bae", "Let's Not Fall in Love"],
    "G-Dragon": ["Crooked", "Heartbreaker", "One of a Kind"],
    "PSY": ["Gangnam Style", "That That", "Daddy"],
    "Rain": ["Rainism", "Love Song", "It's Raining"],
    "BoA": ["No.1", "Only One", "Woman"],
    "TVXQ!": ["Mirotic", "Keep Your Head Down", "Catch Me"],
    "Super Junior": ["Sorry, Sorry", "Mr. Simple", "Devil"],
    "Girls' Generation": ["Gee", "The Boys", "I Got a Boy"],
    "2NE1": ["I Am the Best", "Lonely", "Come Back Home"],
    "EXO": ["Growl", "Love Shot", "Call Me Baby"],
    "NCT 127": ["Kick It", "Sticker", "Cherry Bomb"],
    "NCT DREAM": ["Glitch Mode", "Hello Future", "Hot Sauce"],
    "aespa": ["Next Level", "Savage", "Spicy"],
    "(G)I-DLE": ["Tomboy", "Nxde", "Queencard"],
    "ITZY": ["WANNABE", "DALLA DALLA", "LOCO"],
    "LE SSERAFIM": ["ANTIFRAGILE", "UNFORGIVEN", "FEARLESS"],
    "IVE": ["LOVE DIVE", "After LIKE", "I AM"],
    "AKMU": ["200%", "How can I love the heartbreak, you're the one I love", "Dinosaur", "Last Goodbye"],
    "Zico": ["Any Song", "Artist", "Summer Hate"],
    "DEAN": ["instagram", "DIE 4 YOU", "Bonnie & Clyde"],
    "Crush": ["Beautiful", "Don't Forget", "Give It to Me"],
    "Jay Park": ["MOMMAE", "All I Wanna Do", "GANADARA"],
    "Epik High": ["Born Hater", "Love Love Love", "Eternal Sunshine"],
    "Tablo": ["Tomorrow", "Fever's End", "Bad"],
    "Hyuna": ["Bubble Pop!", "Red", "I'm Not Cool"],
    "Sunmi": ["Gashina", "Heroine", "Siren"],
    "Chung Ha": ["Gotta Go", "Roller Coaster", "Snapping"],
    "Somi": ["Birthday", "Fast Forward", "What You Waiting For"],
    "Jessi": ["NUNU NANA", "Cold Blooded", "ZOOM"],
    "MAMAMOO": ["HIP", "Starry Night", "Egotistic"],
    "Apink": ["Mr. Chu", "Dumhdurum", "Remember"],
    "Davichi": ["Don't Say Goodbye", "Turtle", "Missing You Today"],
    "Bol4": ["Workaholic", "Travel", "To My Youth"],
    "10CM": ["Spring Snow", "Pet", "Phonecert"],
    "Paul Kim": ["Every Day, Every Moment", "Me After You", "About Love"],
}


def main() -> None:
    lines: list[str] = []
    seen: set[str] = set()
    for artist, titles in ARTIST_HITS.items():
        for title in titles:
            key = f"{artist.lower()}|{title.lower()}"
            if key in seen:
                continue
            seen.add(key)
            lines.append(f"{artist} - {title}")

    out = Path(__file__).resolve().parents[1] / "data" / "diverse_tracks.txt"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(lines)} tracks to {out}")


if __name__ == "__main__":
    main()
